//variables for the game
const WIDTH = 650;
const HEIGHT = 450;
const SQUARE_SIDE = 50;
const score = document.getElementById(".score");
let cols, rows;
let w = 50;
let vinyl;
let bgImage;
let collector;
let collectorFront;
let collectorBack;
let collectorLeft;
let collectorRight;
let current;
let time = 40;
let gameMusic;
let goodEndMusic;
let badEndMusic;
let background1;
let background2;
let background3;
let goodEnd;
let badEnd;
