const WIDTH = 650;
const HEIGHT = 450;
const SQUARE_SIDE = 50;
let cols, rows;
let w = 50;
let vinyl;
let bgImage;
let collectorFront;
let collectorBack;
let collectorLeft;
let collectorRight;
let current;
let time = 60;
let gameMusic;
